pipeline{
  agent any
  tools {
    maven 'maven'
  }
  stages {
    stage ("initialize") {
      steps {
        sh ''' 
                echo "PATH = ${PATH}
                echo "M2_HOME = ${M2_HOME}
           '''
      }
    }
    stage("build"){
      steps{
        sh "cd devsecops_pipeline/webapp-master"
        sh "mvn clean package"
      }
    }
  }
}
