pipeline{
  agent any
  tools {
    maven 'maven'
  }
  stages {
    stage ("initialize") {
      steps {
        sh ''' 
                echo "PATH = ${PATH}
                echo "M2_HOME = ${M2_HOME}
           '''
      }
    }
    
    stage ("check-git-secrets"){
      steps{
        sh "rm trufflehog || true"
        sh "docker run gesellix/trufflehog --json https://github.com/ghanatava/devsecops_pipeline.git > trufflehog"
        sh "cat trufflehog"
      }
    }
    stage ("SAST"){
      steps{
        withSonarQubeEnv("sonar"){
          sh "cd webapp-master"
          sh "mvn sonar:sonar"
          sh "cat target/sonar/report-task.txt"
        }
      }
    }
    stage("build"){
      steps{
        sh "mvn -f /var/lib/jenkins/workspace/webapp/webapp-master/pom.xml clean package "
      }
    }

    stage ("Deploy"){
      steps{
        sshagent(credentials: ['prod']){
          sh "scp -o StrictHostKeyChecking=no /var/lib/jenkins/workspace/webapp/webapp-master/target/*.war ubuntu@ec2-13-211-212-234.ap-southeast-2.compute.amazonaws.com:/home/ubuntu/prod/apache-tomcat-9.0.84/webapps/webapp.war"
          
        }
      }
    }
  }
}
