pipeline{
  agent any
  tools {
    maven 'maven'
  }
  stages {
    stage ("initialize") {
      steps {
        sh ''' 
                echo "PATH = ${PATH}
                echo "M2_HOME = ${M2_HOME}
           '''
      }
    }
    stage("build"){
      steps{
        sh "mvn -f /var/lib/jenkins/workspace/webapp/webapp-master/pom.xml clean package "
      }
    }
  }
}
